[package]
name = "aftiktuna-macroquad"
edition = "2021"
version.workspace = true

[dependencies]
aftiktuna = { path = ".." }
egui.workspace = true
egui-miniquad = "0.15.0"
macroquad.workspace = true
serde.workspace = true
serde_json.workspace = true
