[package]
name = "aftiktuna-three-d"
edition = "2021"
version.workspace = true

[dependencies]
aftiktuna = { path = ".." }
epaint_default_fonts = "0.29.1"
three-d.workspace = true
three-d-asset = { version = "0.9.2", features = ["png"] }
winit = "0.28"
