[package]
name = "aftiktuna-three-d"
edition = "2021"
version.workspace = true

[dependencies]
aftiktuna = { path = ".." }
epaint_default_fonts = "0.34.3"
rand.workspace = true
three-d.workspace = true
three-d-asset = { version = "0.10.0", features = ["png"] }
winit = "0.28"

[lints.clippy]
bool_to_int_with_if = "warn"
elidable_lifetime_names = "warn"
explicit_deref_methods = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
implicit_clone = "warn"
manual_is_variant_and = "warn"
map_unwrap_or = "warn"
mut_mut = "warn"
redundant_closure_for_method_calls = "warn"
single_char_pattern = "warn"
uninlined_format_args = "warn"
unnecessary_semicolon = "warn"
