[workspace]
members = ["aftiktuna-editor"]

[workspace.package]
version = "0.9.0"

[workspace.dependencies]
egui = "0.28.1"
macroquad = "0.4.5"
serde = "1.0"
serde_json = "1.0"


[package]
name = "aftiktuna"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui.workspace = true
egui-miniquad = "0.15.0"
hecs = { version = "0.10.3", features = ["column-serialize"] }
indexmap = { version = "2.2.6", features = ["serde"] }
macroquad.workspace = true
rand = { version = "0.8.5", features = ["alloc"] }
rmp-serde = "1.1.2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[features]
debug_logging = []
