on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build three-d ${{ matrix.target }}
    runs-on: ${{ matrix.runner-os }}
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu ]
        include:
          - runner-os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            setup-script: sudo apt-get install mingw-w64
    steps:
      - uses: actions/checkout@master
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: Run setup script
        if: matrix.setup-script != null
        run: ${{ matrix.setup-script }}
      - name: Build binary
        run: cargo build --manifest-path=aftiktuna-rust/Cargo.toml --release --target=${{ matrix.target }} --package=aftiktuna-three-d --bin=aftiktuna-three-d
  build-web:
    name: Build with wasm-pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Install wasm-pack
        # `cargo install wasm-pack` is also an option, but a prebuilt binary for the tool seems more fit for purpose
        run: curl https://wasm-bindgen.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build Wasm
        run: wasm-pack build --target web --dev --no-pack --no-opt aftiktuna-rust/aftiktuna-three-d/
