on:
  workflow_dispatch:

jobs:
  release:
    name: Release test ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
        include:
          - target: x86_64-unknown-linux-musl
            pre-build-script: aftiktuna-rust/linux-setup.sh
    steps:
      - uses: actions/checkout@master
      - run: cd aftiktuna-rust
      - name: Compile and release
        uses: kirderf1/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}
          BINARIES: "aftiktuna"
          EXTRA_FILES: "readme.txt assets/"
          PRE_BUILD: ${{ matrix.pre-build-script }}
          UPLOAD_MODE: "none"
      - name: Check output archive
        run: |
          unzip ${BUILT_ARCHIVE} -d unzipped_files
          ls unzipped_files
