on:
  workflow_dispatch:

jobs:
  release:
    name: Release test ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-gnu ]
        include:
          - target: x86_64-unknown-linux-gnu
            setup-script: aftiktuna-rust/linux-setup.sh
    steps:
      - uses: actions/checkout@master
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: Run setup script
        run: "./${{ matrix.setup-script }}"
      - name: Build binary
        run: cargo build --manifest-path aftiktuna-rust/Cargo.toml --release --target ${{ matrix.target }} --bin aftiktuna
      - name: Package files
        run: |
          mkdir output
          cp "aftiktuna-rust/target/${{ matrix.target }}/release/aftiktuna" build-output
          cp aftiktuna-rust/readme.txt build-output
          cp --recursive aftiktuna-rust/assets build-output
          zip -9r "aftiktuna-${{ matrix.target }}.zip" "build-output/aftiktuna build-output/readme.txt build-output/assets"
      - name: Check output archive
        run: |
          unzip "aftiktuna-${{ matrix.target }}.zip" -d unzipped_files
          ls unzipped_files
