on:
  workflow_dispatch:

jobs:
  release:
    name: Release test ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
        include:
          - target: x86_64-unknown-linux-musl
            pre-build-script: aftiktuna-rust/linux-setup.sh
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        id: rust-build
        uses: kirderf1/rust-build.action@v1.0.0
        with:
          RUSTTARGET: ${{ matrix.target }}
          BINARIES: "aftiktuna"
          EXTRA_FILES: "aftiktuna-rust/readme.txt aftiktuna-rust/assets"
          SRC_DIR: "aftiktuna-rust"
          PRE_BUILD: ${{ matrix.pre-build-script }}
          UPLOAD_MODE: "none"
      - name: Check output archive
        run: |
          unzip "${{ steps.rust-build.outputs.BUILT_ARCHIVE }}" -d unzipped_files
          ls unzipped_files
