on:
  workflow_dispatch:

jobs:
  release:
    name: Release test ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: kirderf1/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}
          BINARIES: "aftiktuna"
          EXTRA_FILES: "readme.txt assets/"
          SRC_DIR: "aftiktuna-rust"
          UPLOAD_MODE: "none"
      - name: Check output archive
        run: |
          unzip ${BUILT_ARCHIVE} -d unzipped_files
          ls unzipped_files
